### ISSUE TITLE
Height of the slots on the ribs doesn't change with modified material thickness

### ISSUE THREAD

**Issue by and-hus** [schuderer/svgbuilder#13]
When changing the material thickness, the slots on the sides get narrower, but the slots on the ribs are not adapted to the new thickness:
![Katapult_Thickness_Issue](https://user-images.githubusercontent.com/69750506/236744630-38cdd7fe-de70-4aae-a7ed-edaed7dc90f4.png)

**Comment by and-hus** [comment]
Seems to be a refresh-issues. Reloading the page using f5 updates the height

**Comment by schuderer** [comment]
Thanks @and-hus ! I seem to have introduced this when I introduced properties for `holeWidth` and `holeHeight` to reduce the amount of magic numbers in the design. Unfortunately, these properties currently are only set once in `Bar`'s construtor and then never update. PR welcome! :) I can also fix this as part of the PR I'm preparing for issue #4
